### ISSUE TITLE
下载游戏0B

### ISSUE THREAD

**Issue by qwqaqwqso** [ikunshare/Onekey#13]
下载是0b，怎么办？还有,1.1.4在某些电脑上不可用

**Comment by nightnatcher** [comment]
怎么办？我是1.1.4，Steamtools工作正常，开启了解锁模式，Steam正常，中午的时候还可以正常使用，晚上就不行了，尝试过重启，关闭/打开加速器，求解，急急急！！！
![image](https://github.com/user-attachments/assets/d9c780fc-7d2d-44f2-8867-0c8faa163b7f)

**Comment by ZRen277353** [comment]
> 怎么办？我是1.1.4，Steamtools工作正常，开启了解锁模式，Steam正常，中午的时候还可以正常使用，晚上就不行了，尝试过重启，关闭/打开加速器，求解，急急急！！！ ![image](https://private-user-images.githubusercontent.com/178767100/362803047-d9c780fc-7d2d-44f2-8867-0c8faa163b7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5NzY4NDMsIm5iZiI6MTcyNDk3NjU0MywicGF0aCI6Ii8xNzg3NjcxMDAvMzYyODAzMDQ3LWQ5Yzc4MGZjLTdkMmQtNDRmMi04ODY3LTBjOGZhYTE2M2I3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgzMFQwMDA5MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MDJiODM0MWYwNzc0NGY4OTVhNTZjODUyNGYzMWZkMTU1YzM2MzRmOTU5ZTVhMmZiNTQ2ZDUxMmMzZWZmNGQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0TQjF4ZfVUyDUyQxEweML91XFD1OoERjz4zke0q6P9U)

这个游戏可能还没有人分享清单就会这样提示下载或生成失败

**Comment by ZRen277353** [comment]
> 下载是0b，怎么办？还有,1.1.4在某些电脑上不可用

不可用尝试删除同目录下的配置文件，下显示0b关闭steamtools的禁止游戏更新

**Comment by qwqaqwqso** [comment]
好像是清单失效了

________________________________
发件人: ZRen277353 ***@***.***>
发送时间: 2024年8月30日 8:12
收件人: ikunshare/Onekey ***@***.***>
抄送: qwqaqwqso ***@***.***>; Author ***@***.***>
主题: Re: [ikunshare/Onekey] 下载游戏0B (Issue #13)


下载是0b，怎么办？还有,1.1.4在某些电脑上不可用

不可用尝试删除同目录下的配置文件，下显示0b关闭steamtools的禁止游戏更新

―

**Comment by qwqaqwqso** [comment]
stool新的登录重新登录一下


________________________________
发件人: ZRen277353 ***@***.***>
发送时间: 2024年8月30日 8:11
收件人: ikunshare/Onekey ***@***.***>
抄送: qwqaqwqso ***@***.***>; Author ***@***.***>
主题: Re: [ikunshare/Onekey] 下载游戏0B (Issue #13)


怎么办？我是1.1.4，Steamtools工作正常，开启了解锁模式，Steam正常，中午的时候还可以正常使用，晚上就不行了，尝试过重启，关闭/打开加速器，求解，急急急！！！ [image] <https://private-user-images.githubusercontent.com/178767100/362803047-d9c780fc-7d2d-44f2-8867-0c8faa163b7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5NzY4NDMsIm5iZiI6MTcyNDk3NjU0MywicGF0aCI6Ii8xNzg3NjcxMDAvMzYyODAzMDQ3LWQ5Yzc4MGZjLTdkMmQtNDRmMi04ODY3LTBjOGZhYTE2M2I3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgzMFQwMDA5MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MDJiODM0MWYwNzc0NGY4OTVhNTZjODUyNGYzMWZkMTU1YzM2MzRmOTU5ZTVhMmZiNTQ2ZDUxMmMzZWZmNGQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0TQjF4ZfVUyDUyQxEweML91XFD1OoERjz4zke0q6P9U>

这个游戏可能还没有人分享清单就会这样提示下载或生成失败

―

**Comment by qwqaqwqso** [comment]
> > 下载是0b，怎么办？还有,1.1.4在某些电脑上不可用
> 
> 不可用尝试删除同目录下的配置文件，下显示0b关闭steamtools的禁止游戏更新

这个可以哟
