### ISSUE TITLE
1.1.4无法正常下载清单 报错（已解决）

### ISSUE THREAD

**Issue by ZRen277353** [ikunshare/Onekey#14]
![image](https://github.com/user-attachments/assets/06a81990-5001-46be-80cf-014c78b928b5)
使用1.1.4版本对任意游戏都无法正常进行清单下载，报错内容截图

**Comment by psheep303** [comment]
怎么解决的

**Comment by ZRen277353** [comment]
> 怎么解决的

删除配置文件就可以了
或者把onekey放到一个空文件夹里

**Comment by psheep303** [comment]
出现以下错误
`[Onekey][ERROR] ⚠ 清单下载或生成失败:`
应该怎么做

**Comment by ZRen277353** [comment]
> 出现以下错误 `[Onekey][ERROR] ⚠ 清单下载或生成失败:` 应该怎么做

这个游戏还没有人分享清单或游戏不存在

**Comment by psheep303** [comment]
为什么，我在steamdb上找到了

**Comment by psheep303** [comment]
已解决
