### ISSUE TITLE
国人真的骗国人，信息差很重要！

### ISSUE THREAD

**Issue by Simon-Yi** [ikunshare/Onekey#18]
前两天看到B站有人套壳卖，没想到是开源的。
我被骗了！

**Comment by ikun0014** [comment]
哈哈哈

**Comment by chenqq2016** [comment]
没想到呀没想到

**Comment by AdventCirno** [comment]
国人不骗国人能赚钱,还能从老外那里爆金币不成(狗头

**Comment by XIe-Yibin** [comment]
LYX music 永久卡是源是没有维护了吗， 什么歌曲都听不了

**Comment by ikun0014** [comment]
> LYX music 永久卡是源是没有维护了吗， 什么歌曲都听不了

http://api.ikunshare.com/script?key=卡密

**Comment by ikun0014** [comment]
> LYX music 永久卡是源是没有维护了吗， 什么歌曲都听不了

更新
