### ISSUE TITLE
怎么使用，大佬

### ISSUE THREAD

**Issue by bakciam** [ikunshare/Onekey#2]
贴吧上的关于使用的方式全挂了，大佬能不能补一下，谢谢

**Comment by ikun0014** [comment]
[文档](https://lyvx-my.sharepoint.com/:w:/g/personal/ikun_ikunshare_com/EWqIqyCElLNLo_CKfLbqix0BWU_O03HLzEHQKHdJYrUz-Q?e=dSuiB0)
