### ISSUE TITLE
桌面不是C盘无法创建快捷方式

### ISSUE THREAD

**Issue by Jai7882** [ikunshare/Onekey#21]
因为无法创建快捷方式 不知道自动安装到哪目录 然后每次启动时都需要重新安装 建议动态获取一下系统桌面路径然后再创建快捷方式

**Comment by ikun0014** [comment]
？？？？？？？？？？？？

**Comment by muwenyan521** [comment]
本工具为单文件,无需安装,直接双击主程序使用即可

**Comment by ikun0014** [comment]
> 本工具为单文件,无需安装,直接双击主程序使用即可
