### ISSUE TITLE
一键不起作用

### ISSUE THREAD

**Issue by thecoderboy420** [ikunshare/Onekey#27]
Onekey 应用程序无法运行，我尝试运行它，但所有游戏都显示错误。
![image_2024-09-16_122219083](https://github.com/user-attachments/assets/1cefbe11-3c53-4bf9-b3b7-04fbac1a266e)

**Comment by muwenyan521** [comment]
Github API 请求数已用尽,请等待重置或参照[增加剩余请求次数](https://ikunshare.com/d/64)进行重新生成

**Comment by ikun0014** [comment]
> Github API 请求数已用尽,请等待重置或参照[增加剩余请求次数](https://ikunshare.com/d/64)进行重新生成
