### ISSUE TITLE
镜像源

### ISSUE THREAD

**Issue by muwenyan521** [ikunshare/Onekey#31]
以下是我收集的可用镜像源（截至2024/9/17，除去Onekey已含）：
        1. https://raw.kkgithub.com/{repo}/{sha}/{path}
        2. https://gitdl.cn/https://raw.githubusercontent.com/{repo}/{sha}/{path}
        3. https://ghp.ci/https://raw.githubusercontent.com/{repo}/{sha}/{path}
        4. https://ghproxy.net/https://raw.githubusercontent.com/{repo}/{sha}/{path}
        5. https://fastly.jsdelivr.net/gh/{repo}@{sha}/{path}
        6. https://jsdelivr.pai233.top/gh/{repo}@{sha}/{path}
可能5 6我写的请求方式错误，不过应该大都是对的

**Comment by hcllmsx** [comment]
所以这个要添加到哪里呢....
