### ISSUE TITLE
关于清单仓库

### ISSUE THREAD

**Issue by qwqaqwqso** [ikunshare/Onekey#34]
作者，更新仓库慢一点，动不动用不了T_T

**Comment by qwqaqwqso** [comment]
报错KeyError: 'Github_Personal_Token'

**Comment by lund1122** [comment]
drdr game error 
![Screenshot 2024-09-21 142323](https://github.com/user-attachments/assets/c22594bc-7b5e-475f-8c38-f4ad3cf16af7)

**Comment by kobeman8** [comment]
求添加993090和 1114150 感谢作者

**Comment by qwqaqwqso** [comment]
求gta4r星启动器报1000.50

**Comment by lund1122** [comment]
plz help
