### ISSUE TITLE
无法正常使用

### ISSUE THREAD

**Issue by lff110** [ikunshare/Onekey#38]
![1](https://github.com/user-attachments/assets/86328636-0abc-44e4-8e3b-7d697678bc3d)

**Comment by nihaodaming** [comment]
这是"Custom_Steam_Path"填写的路径有问题,要用两个反斜杠

**Comment by lff110** [comment]
> 这是"Custom_Steam_Path"填写的路径有问题,要用两个反斜杠
好吧，今天起来试试
