### ISSUE TITLE
关于使用次数

### ISSUE THREAD

**Issue by ChenDennis2013** [ikunshare/Onekey#5]
# 请问使用次数不够了怎么自己弄啊啊啊

**Comment by ioioRhys** [comment]
全网都没有教程，只有作者知道吧

**Comment by ikun0014** [comment]
docs.github.com

**Comment by KBchulan** [comment]
按下面的做就行：登录GitHub账户： 打开浏览器并访问[GitHub](https://github.com/)，然后使用你的账户登录。

进入设置页面： 点击页面右上角的头像，然后选择“Settings”（设置）。

导航到开发者设置： 在设置页面的左侧菜单中，向下滚动并找到“Developer settings”（开发者设置），点击进入。

选择个人访问令牌： 在开发者设置页面中，点击“Personal access tokens”（个人访问令牌）。

生成新令牌： 如果你还没有个人访问令牌，可以点击“Generate new token”（生成新令牌）。如果已经有令牌，可以直接使用现有的令牌。

配置令牌权限： 在生成新令牌的页面中，为令牌设置一个描述性的名称，并选择你需要的权限范围。通常，对于大多数自动化任务，选择repo和workflow权限就足够了。

生成令牌： 点击页面底部的“Generate token”（生成令牌）按钮。

复制令牌： 生成令牌后，GitHub会显示你的新令牌。请务必立即复制这个令牌，因为它只会显示一次。

保存令牌： 将复制的令牌粘贴到你的配置文件config.json中的Github_Personal_Token字段中。

示例配置文件更新如下：

{
  "Github_Personal_Token": "你的个人访问令牌",
  "Custom_Steam_Path": "",
  "QA1": "温馨提示：Github_Personal_Token可在Github设置的最底下开发者选项找到，详情看教程",
  "教程": "https://lyvx-my.sharepoint.com/:w:/g/personal/ikun_ikunshare_com/EWqIqyCElLNLo_CKfLbqix0BWU_O03HLzEHQKHdJYrUz-Q?e=79MZjw"
}

**Comment by qwqaqwqso** [comment]
其实我使用次数每天都重置一次………………………………
