### ISSUE TITLE
[BUG]: 清单下载或生成失败：2688950

### ISSUE THREAD

**Issue by HanHanDeYaYa** [ikunshare/Onekey#53]
**触发Bug后出现了什么症状**
1.提示：“清单下载或生成失败: 2688950”

**如何复现该Bug**
步骤:
1. 下载ID：2688950
2. 报错失败

**日志**
尚不知道
**截图**
![image](https://github.com/user-attachments/assets/7335ece4-fd82-4f5d-8d77-e6d9dff7307e)

**系统:**
 - OS: Windows
 - Version: 11

**备注**
最新版同样报错

**Comment by HanHanDeYaYa** [comment]
@ikun0014

**Comment by ikun0014** [comment]
此游戏未收录

**Comment by HanHanDeYaYa** [comment]
> 此游戏未收录

请问可以收录他吗？
@ikun0014
