### ISSUE TITLE
指定的网络名不可再用

### ISSUE THREAD

**Issue by vipyzr** [ikunshare/Onekey#8]
![Uploading 屏幕截图 2024-08-19 204155.png…]()
![屏幕截图 2024-08-19 204204](https://github.com/user-attachments/assets/9bd45c87-dea6-459a-8a20-219d1d4aeb82)
![Uploading 屏幕截图 2024-08-19 204227.png…]()

**Comment by ikun0014** [comment]
什么逆天问题😂

**Comment by qwqaqwqso** [comment]
这个是没清单，@作者补清单即可

**Comment by ikun0014** [comment]
你这就网络问题，自行解决
